### ISSUE TITLE
u and v may be NaN from the beginning

### ISSUE THREAD

**Issue by VanillaWhey** [dhruvramani/Transformers-RL#3]
At first, thanks for the great implementation.

I found that this initialization is somewhat critical:
https://github.com/dhruvramani/Transformers-RL/blob/fc3d8af2f9b2ffc055855c755a1c892e4ae359d2/layers.py#L256

It may occur that self.u and self.v will be initialized containing nan. Eventually, this leads to everything becoming nan.

**Comment by dhruvramani** [comment]
Thanks for the PR!
